#!/usr/bin/env bash
# MitoRiboPy rpf -- exhaustive shell-script template (rpf stage only).
# Compatible with: MitoRiboPy 0.7.0+
#
# Runs only the rpf stage:
#
#   BED (or BAM) input -> filter on RPF length window
#                      -> offset enrichment (combined + per-sample)
#                      -> offset selection
#                      -> translation_profile/<sample>/{p,a}/...
#                      -> coverage_profile_plots/{read_coverage_*, {p_site,a_site}_density_*}/
#                      -> optional: structure_density, codon_correlation
#
# Inputs assumed (from a prior `mitoribopy align` run, or generated by
# any aligner that emits per-sample BED6 against the same FASTA):
#   - <BED_DIR>/<sample>.bed                   (strand-aware BED6, REQUIRED)
#   - <READ_COUNTS_FILE> (optional but recommended for RPM normalization)
#   - <MT_FASTA>                                (REQUIRED; same FASTA the
#                                                 BEDs were aligned to)
#
# Quick start:
#   1. Edit the variables in the "Edit me" block below.
#   2. chmod +x run_rpf.example.sh
#   3. ./run_rpf.example.sh
#
# Default values match `mitoribopy rpf --help` defaults; delete any
# line you do not need to override. Lines starting with `#` are
# commented-out optional flags; uncomment to enable.
set -euo pipefail

# ============================================================================
# Edit me
# ============================================================================
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Inputs (REQUIRED)
MT_FASTA="${PROJECT_ROOT}/input_data/human-mt-mRNA.fasta"
BED_DIR="${PROJECT_ROOT}/results/align/bed"

# Optional but recommended -- enables RPM normalization. Comment out the
# --read-counts-file line below if you do not have one.
READ_COUNTS_FILE="${PROJECT_ROOT}/results/align/read_counts.tsv"

# Output directory.
OUTPUT_DIR="${PROJECT_ROOT}/results/rpf"

# Compute knobs.
THREADS=8
LOG_LEVEL=INFO            # DEBUG | INFO | WARNING | ERROR


# ============================================================================
# rpf  --  BED -> offsets + translation profile + coverage plots
# ============================================================================
RPF_OPTS=(
  # --- Core inputs / outputs ---------------------------------------------
  --fasta "${MT_FASTA}"
  --directory "${BED_DIR}"
  --read-counts-file "${READ_COUNTS_FILE}"
  --output "${OUTPUT_DIR}"
  --bam-mapq 10                    # MAPQ threshold for BAM inputs (BAM->BED6)

  # --- Organism / strain -------------------------------------------------
  --strain h.sapiens               # h.sapiens | s.cerevisiae | custom
                                   # Synonyms `h` and `y` are accepted.
  # --annotation-file "${PROJECT_ROOT}/my_annotation.csv"
                                   # REQUIRED for --strain custom; columns:
                                   # transcript, l_tr, l_utr5, l_utr3 (+ optional
                                   # l_cds, sequence_name, sequence_aliases,
                                   # display_name)
  # --codon-tables-file "${PROJECT_ROOT}/my_codons.json"
                                   # only when your code is not in the bundled NCBI list
  # --codon-table-name vertebrate_mitochondrial
                                   # NCBI Genetic Code name (e.g. mold_mitochondrial,
                                   # invertebrate_mitochondrial, ...). Run
                                   # `mitoribopy rpf --help` for the full list.
  # --start-codons ATG ATA         # override strain default
  --atp8-atp6-baseline ATP6        # ATP6 | ATP8
  --nd4l-nd4-baseline ND4          # ND4  | ND4L

  # --- RPF length window -------------------------------------------------
  --footprint-class monosome       # short | monosome | disome | custom
                                   # short:    h.sapiens / s.cerevisiae 16-24 nt
                                   # monosome: h.sapiens 28-34, s.cerevisiae 37-41
                                   # disome:   h.sapiens 50-70, s.cerevisiae 60-90
  -rpf 29 34                       # explicit [min, max] (overrides footprint_class)
  --unfiltered-read-length-range 15 50

  # --- Offset enrichment / selection -------------------------------------
  --align stop                     # start | stop -- which anchor codon to align to
  --range 20                       # plot offsets from -range to +range
  --min-offset 11                  # shared min absolute offset (legacy fallback)
  --max-offset 20                  # shared max absolute offset (legacy fallback)
  --rpf-min-count-frac 0.20        # auto-prune read-length bins below 20% of the
                                   # most-enriched length's count (set 0 to disable).
  --min-5-offset 10                # end-specific 5' min (preferred)
  --max-5-offset 22                # end-specific 5' max
  --min-3-offset 10                # end-specific 3' min
  --max-3-offset 22                # end-specific 3' max
  --offset-mask-nt 5               # mask -N..-1 and +1..+N near the anchor codon
  --offset-pick-reference p_site   # p_site | reported_site
  --offset-type 5                  # 5 | 3 -- which read end the offset is measured from
  --offset-site p                  # p | a -- coordinate space of the SELECTED OFFSETS table
  --analysis-sites both            # p | a | both -- which downstream sites to generate
  --codon-overlap-mode full        # full | any
  # --psite-offset 12              # fixed offset for every read length (bypass enrichment)
  --offset-mode per_sample         # per_sample | combined

  # --- Outputs / plotting ------------------------------------------------
  --downstream-dir footprint_density
  --plot-dir offset_diagnostics    # CSVs go to <plot_dir>/csv/, plots to <plot_dir>/plots/.
                                   # Per-sample offsets at <plot_dir>/csv/per_sample_offset/.
  --plot-format svg                # png | pdf | svg
  --line-plot-style combined       # combined | separate
  --cap-percentile 0.999
  --codon-density-window           # smooth codon-density with +/-1 nt window
  # --x-breaks 10 20 30            # custom x-axis tick marks for offset line plots
  # --order-samples ctrl_1 ctrl_2 kd_1 kd_2

  # --- Read-count normalization -----------------------------------------
  --rpm-norm-mode total            # total | mt_mrna
  --mt-mrna-substring-patterns mt_genome mt-mrna mt_mrna
  # --read-counts-sample-col Sample
  # --read-counts-reads-col Reads
  # --read-counts-reference-col Reference

  # --- Optional modules --------------------------------------------------
  # --structure-density
  # --structure-density-norm-perc 0.99
  --cor-plot                       # publication-quality codon-correlation scatter,
                                   # one folder per requested site (P, A) when both
                                   # are generated.
  --base-sample WT_R1              # required by --cor-plot; change to YOUR reference.
  # --cor-mask-method percentile   # percentile | fixed | none
  # --cor-mask-percentile 0.99
  # --cor-mask-threshold 1.5

  # --- Read-coverage outputs (default: both raw and rpm) ------------------
  --no-read_coverage_raw           # skip read_coverage_raw[_codon]/ folders.
                                   # The RPM track below is what most users want.
  --read-coverage-rpm              # write read_coverage_rpm[_codon]/ folders.
  --igv-export                     # write IGV-loadable BedGraph tracks under
                                   # igv_tracks/<sample>/<sample>_{p,a}_site.bedgraph.

  # --- Shared --------------------------------------------------------------
  --threads "${THREADS}"
  --log-level "${LOG_LEVEL}"
)

mitoribopy rpf "${RPF_OPTS[@]}"


# ============================================================================
# Done
# ============================================================================
echo
echo "MitoRiboPy rpf finished."
echo "Inspect outputs under: ${OUTPUT_DIR}/"
echo
echo "Key files to look at first:"
echo "  ${OUTPUT_DIR}/offset_diagnostics/plots/offset_drift_*.svg"
echo "                                        # per-sample offset comparison; READ THIS FIRST"
echo "  ${OUTPUT_DIR}/offset_diagnostics/plots/offset_*.svg"
echo "                                        # combined enrichment heatmap + line plots"
echo "  ${OUTPUT_DIR}/offset_diagnostics/csv/p_site_offsets_*.csv"
echo "                                        # combined selected offsets"
echo "  ${OUTPUT_DIR}/offset_diagnostics/csv/per_sample_offset/<sample>/offset_applied.csv"
echo "                                        # exact offset row applied to each sample"
echo "  ${OUTPUT_DIR}/translation_profile/<sample>/codon_usage/p_site_codon_usage_total.csv"
echo "                                        # P-site codon occupancy"
echo "  ${OUTPUT_DIR}/translation_profile/<sample>/codon_usage/a_site_codon_usage_total.csv"
echo "                                        # A-site codon occupancy"
echo "  ${OUTPUT_DIR}/coverage_profile_plots/p_site_density_rpm_frame/<gene>_*.svg"
echo "                                        # frame-coloured CDS-only nt plots; frame-0"
echo "                                        # dominance is the canonical mt-Ribo-seq QC"
echo "  ${OUTPUT_DIR}/codon_correlation/{p_site,a_site}/<base>_vs_<sample>_*.{svg,png}"
echo "                                        # publication-quality codon scatters"
echo "  ${OUTPUT_DIR}/igv_tracks/<sample>/<sample>_{p_site,a_site}.bedgraph"
echo "                                        # IGV-loadable footprint density tracks"
echo "  ${OUTPUT_DIR}/mitoribopy.log          # per-step timing for the 7 rpf steps"
echo "                                        # plus the end-of-run [PIPELINE] Timing"
echo "                                        # summary (per-step duration + wall)."
