#!/usr/bin/env python3
"""Generate a Mermaid architecture flowchart for the MitoRiboPy package.

This script writes the diagram source to:
  docs/diagrams/mitoribopy_package_flow.mmd

The diagram is intentionally high-level and follows the current package
execution path used by `mitoribopy`.
"""

from __future__ import annotations

from pathlib import Path


DIAGRAM_TEXT = """%% Auto-generated by docs/diagrams/generate_mitoribopy_diagram.py
flowchart TD
  %% Entry path
  U[\"User command\\n(mitoribopy / python -m mitoribopy)\"]:::entry
  M[\"mitoribopy.__main__\"]:::entry
  C[\"mitoribopy.cli.main\"]:::entry
  R[\"mitoribopy.pipeline.runner.run_pipeline_cli\"]:::entry
  L[\"mitoribopy.pipeline.runner\\n(parse args + run_pipeline)\"]:::core

  U --> M --> C --> R --> L

  %% Core package modules
  subgraph Core_Modules[\"Core Modules Used by Pipeline\"]
    CFG[\"mitoribopy.config\\n(DEFAULT_CONFIG / load_user_config / resolve_rpf_range)\"]
    DATA[\"mitoribopy.data\\n(reference_data + packaged CSV/JSON files)\"]
    IO[\"mitoribopy.io\\n(read_counts, bed_reader)\"]
    OFF[\"mitoribopy.analysis.offset_enrichment\"]
    SEL[\"mitoribopy.analysis.offset_selection\"]
    TPA[\"mitoribopy.analysis.translation_profile_analysis\"]
    COR[\"mitoribopy.analysis.codon_correlation\"]
    RNA[\"mitoribopy.analysis.rna_seq\"]
    PSTYLE[\"mitoribopy.plotting.style\"]
    PVIZ[\"mitoribopy.plotting.visualization\"]
    PCOV[\"mitoribopy.plotting.coverage_profile_plots\"]
    PSD[\"mitoribopy.plotting.structure_density_export\"]
  end

  L --> CFG
  L --> DATA
  L --> IO
  L --> OFF --> SEL
  L --> TPA
  L --> PVIZ
  L --> PCOV
  L --> PSTYLE

  L -. \"optional: --cor_plot\" .-> COR
  L -. \"optional: --use_rna_seq\" .-> RNA
  L -. \"optional: --structure_density\" .-> PSD

  %% Outputs
  subgraph Outputs[\"Primary Outputs\"]
    O1[\"plots_and_csv/\\n(read-length summaries, offset CSV/plots)\"]:::out
    O2[\"sample_name/footprint_density/\\nsample_name/codon_usage/\\nsample_name/translating_frame/\"]:::out
    O3[\"coverage_profile_plots/\"]:::out
    O4[\"codon_correlation/\"]:::out
    O5[\"structure_density/\"]:::out
    O6[\"rna_seq_results/\"]:::out
  end

  IO --> O1
  OFF --> O1
  SEL --> O1
  TPA --> O2
  PCOV --> O3
  COR --> O4
  PSD --> O5
  RNA --> O6

  %% Utility tools (independent CLIs)
  subgraph Utility_Tools[\"Utility Tools\"]
    T1[\"mitoribopy.tools.subsample\"]:::tool
    T2[\"mitoribopy.tools.read_composition\"]:::tool
  end

  U -. \"standalone usage\" .-> T1
  U -. \"standalone usage\" .-> T2

  classDef entry fill:#e8f0fe,stroke:#1a73e8,stroke-width:1px,color:#111;
  classDef core fill:#e6f4ea,stroke:#188038,stroke-width:1px,color:#111;
  classDef out fill:#fff4e5,stroke:#ea8600,stroke-width:1px,color:#111;
  classDef tool fill:#f3e8fd,stroke:#9334e6,stroke-width:1px,color:#111;
"""


def main() -> None:
    repo_root = Path(__file__).resolve().parents[2]
    output_path = repo_root / "docs" / "diagrams" / "mitoribopy_package_flow.mmd"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(DIAGRAM_TEXT, encoding="utf-8")
    print(f"[diagram] wrote Mermaid source: {output_path}")


if __name__ == "__main__":
    main()
